apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: dalleclient
  name: dalleclient
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dalleclient
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/project-ai-mern-image-generation-default: "true"
        io.kompose.service: dalleclient
    spec:
      containers:
        - image: dalle-client
          name: dalleclient
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
