apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: dalleserver
  name: dalleserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dalleserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/project-ai-mern-image-generation-default: "true"
        io.kompose.service: dalleserver
    spec:
      containers:
        - env:
            - name: CLOUDINARY_API_KEY
              value: "138197961365755"
            - name: CLOUDINARY_API_SECRET
              value: haIFYRbv0cpiik4_M6o1r58dMt0
            - name: CLOUDINARY_CLOUD_NAME
              value: dall-e-showcase
            - name: MONGODB_URL
              value: mongodb://root:Pssw0rd1@mongo:27017
            - name: OPENAI_API_KEY
              value: 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
          image: dalle-server
          name: dalleserver
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
