version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dall-e
      MONGO_INITDB_ROOT_PASSWORD: Pssw0rd1
      MONGO_INITDB_ROOT_USERNAME: root
  
  dalleserver:
    image: 'dalle-server'
    build: ./server
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://root:Pssw0rd1@mongo:27017
      OPENAI_API_KEY: 
      CLOUDINARY_CLOUD_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
  
  dalleclient:
    image: 'dalle-client'
    build: ./client
    restart: always
    ports:
      - 8000:80
    depends_on:
      - dalleserver